/* Tweakit — build the kit (TypeScript source). One source, several outputs:
 *   • dist/tweaks/      minified, esbuild code-split chunks (TW_SPLIT=true) — the
 *                       core entry + a chunk per lazy control + a shared chunk; basic
 *                       panels fetch core + shared, heavy controls load on demand.
 *   • dist/tweaks.js    one self-contained file (TW_SPLIT=false → every control inlined,
 *                       synchronous) — the drop-in / copyable build, no bundler needed.
 *   • dist/tweaks.css   minified panel CSS.
 *   • dist/types/       .d.ts declarations (tsc) — consumers get full types.
 *   • dist/*.html       the docs/examples site (GitHub Pages root) — see site/.
 * TW_SPLIT is an esbuild `define` that picks the split vs inlined code path in core.ts.
 */
import { mkdir, rm, readFile, writeFile } from "node:fs/promises";
import { gzipSync } from "node:zlib";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import path from "node:path";
import { fileURLToPath } from "node:url";

const run = promisify(execFile);
const ROOT = path.dirname(fileURLToPath(import.meta.url));
const p = (...s) => path.join(ROOT, ...s);
const fail = (msg) => { console.error("✗ " + msg); process.exit(1); };

await rm(p("dist"), { recursive: true, force: true });
await mkdir(p("dist"), { recursive: true });

const esbuild = await import("esbuild");

// 1) code-split, minified chunks → dist/tweaks/ (metafile: so we can find the shared
// chunk core statically imports, to report the real code-split size below)
const splitBuild = await esbuild.build({
  entryPoints: [p("src/tweaks/core.ts")],
  outdir: p("dist/tweaks"),
  bundle: true, splitting: true, format: "esm", minify: true, target: "es2020",
  legalComments: "none", define: { TW_SPLIT: "true" }, metafile: true,
});

// 2) single self-contained file → dist/tweaks.js (every control inlined, synchronous —
// the drop-in that needs no bundler). Minified: it's the default `tweakit` import,
// so it ships small; the readable reference is the src/ tree it's built from.
await esbuild.build({
  entryPoints: [p("src/tweaks/single.ts")],
  outfile: p("dist/tweaks.js"),
  bundle: true, splitting: false, format: "esm", minify: true, target: "es2020",
  legalComments: "none", define: { TW_SPLIT: "false" },
  // The single file is the one people copy into a project, so it carries the notices
  // the MIT and ISC licenses require in every copy (the split build is installed, and
  // the package ships THIRD-PARTY-NOTICES.md next to it).
  banner: { js: "/* tweakit — MIT © Ryan Kiley. Toolbar and control icons from Lucide (ISC) and Feather (MIT); see THIRD-PARTY-NOTICES.md in the tweakit package. */" },
});

// 3) minified panel CSS → dist/tweaks.css. The light palette must exist twice —
// media-driven and attribute-forced ([data-tw-scheme="light"]); CSS can't share one
// block across a media query and a selector. Only the media-driven block is authored:
// the forced twin is GENERATED here from the `@media (prefers-color-scheme: light)`
// block — each `:not([data-tw-scheme="dark"] …)` guard maps to its positive
// `[data-tw-scheme="light"] …` form, emitted right after the media block (source
// order matters: after the dark defaults, so at equal specificity the forced values
// win). Generated, so the two copies can never drift.
{
  // Work on comment-stripped CSS throughout: the minifier drops comments anyway, and a
  // brace inside one would otherwise throw the block scan off.
  const css = (await readFile(p("src/tweaks.css"), "utf8")).replace(/\/\*[\s\S]*?\*\//g, "");
  if (/\[data-tw-scheme="light"\]/.test(css)) fail('src/tweaks.css: hand-written [data-tw-scheme="light"] rule found — the forced-light twin is generated by build.mjs; author only the media-driven block.');
  const MEDIA = "@media (prefers-color-scheme: light)";
  if (!css.includes(MEDIA)) fail("src/tweaks.css: light-scheme media block not found.");
  // Every light media block gets a twin, emitted right after it, so a second block added
  // anywhere in the file is covered the same way as the first.
  let out = "", from = 0, pairs = 0;
  for (let start = css.indexOf(MEDIA); start !== -1; start = css.indexOf(MEDIA, from)) {
    const open = css.indexOf("{", start);
    let i = open + 1;
    for (let depth = 1; i < css.length && depth; i++) { if (css[i] === "{") depth++; else if (css[i] === "}") depth--; }
    const inner = css.slice(open + 1, i - 1);
    // Every rule inside the media block must carry a :where() dark-guard on EACH selector
    // of a comma list — an unguarded selector would generate into the forced block
    // verbatim and apply in every scheme.
    for (const m of inner.matchAll(/([^{}]+)\{[^{}]*\}/g)) {
      for (const sel of m[1].split(",").map((x) => x.trim()).filter(Boolean)) {
        if (!/:where\((?::not\(\[data-tw-scheme="dark"\](?: \*)?\))+\)/.test(sel)) fail(`src/tweaks.css: selector in the light media block without a :where(:not([data-tw-scheme="dark"] …)) guard — its forced twin can't be derived.\n  selector: ${sel.replace(/\s+/g, " ")}`);
      }
    }
    const forced = inner.replace(/:where\(((?::not\(\[data-tw-scheme="dark"\](?: \*)?\))+)\)/g, (_, guards) => {
      pairs++;
      const parts = [...guards.matchAll(/:not\(\[data-tw-scheme="dark"\]( \*)?\)/g)].map((g) => `[data-tw-scheme="light"]${g[1] || ""}`);
      return `:where(${parts.join(", ")})`;
    });
    out += css.slice(from, i) + "\n/* Attribute-forced light — generated from the media block above. */" + forced + "\n";
    from = i;
  }
  out += css.slice(from);
  if (pairs < 1) fail("src/tweaks.css: no :where() dark-guard found in the light media block — the twin system dropped out.");
  const { code } = await esbuild.transform(out, { minify: true, loader: "css" });
  await writeFile(p("dist/tweaks.css"), code);
  // A side-effect type declaration for the `./css` subpath export so a TS
  // consumer can `import "tweakit/css"` without TS2307 — a bare package-subpath
  // import isn't matched by a global `*.css` ambient. The file itself is CSS;
  // this just lets TypeScript resolve the module.
  await writeFile(
    p("dist/tweaks.css.d.ts"),
    '// tweakit/css — the panel stylesheet, imported for its side effect:\n//   import "tweakit/css";\nexport {};\n'
  );
}

// 4) .d.ts declarations → dist/types/ (consumer types; tsc, declaration-only)
try {
  await run("node", ["node_modules/typescript/bin/tsc"], { cwd: ROOT });
  console.log("emitted .d.ts → dist/types/");
} catch (e) {
  fail("tsc failed — the declarations would be wrong or partial:\n" + String(e.stdout || e.message || "").trimEnd());
}

// 4b) measured gzip sizes → the docs site fills {{size-split}} / {{size-single}} with
// these, so the figures can't drift from the build. Split = the core entry + the shared
// chunk it statically imports (what a basic panel fetches); single = the inlined drop-in.
// Heavy controls dynamic-import (kind "dynamic-import") and aren't counted.
const gz = async (rel) => gzipSync(await readFile(p(rel))).length;
const coreOut = Object.keys(splitBuild.metafile.outputs).find((k) => k.endsWith("tweaks/core.js"));
const sharedChunks = (splitBuild.metafile.outputs[coreOut].imports || []).filter((im) => im.kind === "import-statement").map((im) => im.path);
let splitBytes = await gz(coreOut);
for (const c of sharedChunks) splitBytes += await gz(c);
const kb = (b) => `~${Math.round(b / 1024)} KB`;
const sizes = { split: kb(splitBytes), single: kb(await gz("dist/tweaks.js")) };
console.log(`sizes (gzip): code-split ${sizes.split} (core + shared chunk) · single ${sizes.single}`);

// 5) docs site → dist/*.html + site.css/site.js (GitHub Pages serves dist/). The
// generator imports site/pages/*.mjs raw — they never pass through esbuild (each
// example's run function is toString()-serialized into both the snippet and the page
// script, so transpiling would break snippet/runtime parity).
const { buildSite } = await import("./site/build-site.mjs");
await buildSite({ outDir: p("dist"), esbuild, sizes });

console.log("Built tweakit → dist/");
